### ISSUE TITLE
Import File

### ISSUE THREAD

**Issue by utznicholas** [sotheanith/SpotyMusic#33]
We need an import file UI
We should also have a thing to list files imported by other users that aren't in the current user's library.
We'll need to modify the library.importFile() method, and the code backing it.
The file import UI will have to collect the track title, album title, and artist name from the user. It should remember the album title and artist name from the most recently imported file to smoothen the user experience. Track title can be inferred from the name of the file being imported, but the user should be able to modify it before the file is imported.

**Comment by utznicholas** [comment]
Also, we should add the `/SpotyMusic` directory to `.gitignore` when file importing works, so that we don't end up pushing our libraries to each other, which doesn't go well. Especially with large, uncompressed `.wav` files.

**Comment by sotheanith** [comment]
#50 Completed
